# merge_config.yml
# Configuration for mergekit, created by setup_agi_terminal.py
# Based on latest model recommendations.

slices:
  - sources:
      - model: ./models/mistral7b_v03 # mistralai/Mistral-7B-Instruct-v0.3
      - model: ./models/deepseek_coder_v2_lite # deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct (16B)
      - model: ./models/starcoder2_7b # bigcode/starcoder2-7b
      - model: ./models/phi4_mini_instruct # microsoft/Phi-4-mini-instruct (4B)
merge_method: linear
base_model: ./models/mistral7b_v03 # Using Mistral-7B-Instruct-v0.3 as the base
parameters: {}
dtype: float16

# To include other downloaded models like llama3 (./models/llama3),
# bloom (./models/bloom), or gpt_neox (./models/gpt_neox),
# add them to the `sources` list above. Example:
#      - model: ./models/llama3
#      - model: ./models/gpt_neox
